apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-nginx
        image: ghcr.io/kx-ops/thinkphp:b776e9dc63f7851d45a9a4c32bee5bec8e92e6b3
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-login-secret 