apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-nginx
        image: ghcr.io/kx-ops/thinkphp:f54ad24b9d9a31b502e3a3b6610fd2682140b959
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-login-secret # 必须配置，否则无法从 GitHub Packages 拉取镜像