apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-nginx
        image: ghcr.io/kx-ops/thinkphp:e9f6b610cd8b2d93a673a1b274537133cff0f55f
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-login-secret # 必须配置，否则无法从 GitHub Packages 拉取镜像